### ISSUE TITLE
Swagger spec is broken

### ISSUE THREAD

**Issue by john-tipper** [grafeas/grafeas#379] opened 2019-09-15 09:30 UTC
## Expected Behavior
Swagger spec should be valid against Swagger spec.

## Actual Behavior
The path parameters are invalid, e.g. https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/swagger/grafeas.swagger.json#L18, leading to errors such as:

    Declared path parameter "name=projects/*/notes/*" needs to be defined as a path parameter at either the path or operation level

The path parameters should simply be enclosed in `{}`.

## Steps to Reproduce the Problem
Validate `grafeas.swagger.json` against swagger spec, e.g. by copying here: https://editor.swagger.io

**Comment by vtsao** [comment] 2019-09-16 14:16
Thanks @john-tipper for filing this, I should have filed an issue for this sooner. This is due to the Grafeas API using the [Google HTTP annotations](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto) to describe the REST API HTTP bindings.

The Google HTTP syntax is [not compatible with OpenAPI](https://github.com/OAI/OpenAPI-Specification/issues/892), which is what Swagger uses. Also see https://github.com/grpc-ecosystem/grpc-gateway/issues/407.

One of the main reasons we generate a Swagger spec right now is so we can use Swagger to generate client libraries for Grafeas. But since the Swagger spec is broken, this isn't helpful.

We're still thinking about what to do here.

**Comment by vtsao** [comment] 2019-09-16 14:16
FYI @aysylu

**Comment by aysylu** [comment] 2019-09-16 14:57
Thanks for filing the issue, @john-tipper, and for chiming in with context, @vtsao! The contributions to improve this, either at the Grafeas client spec level or at the larger Swagger level are welcome.

**Comment by psprings** [comment] 2019-11-07 05:39
Since this has some overlap with an issue I raised in the [client-go](https://github.com/grafeas/client-go) repository (https://github.com/grafeas/client-go/issues/13) I think it would be worth modifying the generated Swagger spec files as part of the `go generate` process in this repo.

Obviously, a less hacky approach would be preferred longterm, but it's better than having broken specs and clients.

I threw together a really basic way of achieving this and tested a generated client using that approach: https://github.com/grafeas/client-go/pull/15
This could be adapted to do the Swagger spec fixes in this repo and/or integrate into a CI process to automatically generate clients in any number of languages as part of a tag/release process.

I was also looking at doing an optional merge of the different spec files as part of this process, because right now the `grafeas.swagger.json` is the only one being used to generate the Golang client (as an example). It would be nice to use one client to be able to interact with the entire API.

Any thoughts?

**Comment by psprings** [comment] 2020-02-11 18:59
@aysylu @vtsao if you have any thoughts on my above comment, I'd be happy to help contribute a fix whether it is to the [client-go](https://github.com/grafeas/client-go) repository or to this repository.

**Comment by aysylu** [comment] 2020-02-13 23:01
Hi @psprings: thanks for following up on this and apologies for the delay. I thought that I had sent my review for the open PR a while ago, but the comments were sitting in the unfinished review, sorry about that. The `client-go` PR looks good, and I'm looking forward to doing another review and merging it, once it's ready.

Also, I'm open to your contribution of the fix to this repository as well. Overall, I like the approach, and unless we discover this causes issues for clients in other languages (which I do not foresee at the moment), this is a strict improvement over the current state.

Thank you!

**Comment by psprings** [comment] 2020-02-14 16:04
@aysylu no worries -- pretty sure I've done that before. It's been a little bit so I'll revisit the code and address the feedback on the PR.

**Comment by aethanol** [comment] 2022-01-13 16:31
This is finally (almost) fixed in grpc-gateway! https://github.com/grpc-ecosystem/grpc-gateway/pull/2461
There was a small regression that would affect grafeas: https://github.com/grpc-ecosystem/grpc-gateway/issues/2489 but this is a near term fix.

**Comment by aysylu** [comment] 2022-01-13 19:28
@aethanol thanks for looking into this! Adding @wkozlik to this thread, as I moved to another project.

**Closed** 2022-01-24 14:32 UTC
