### ISSUE TITLE
[Question] How does v1beta1 swagger path parameter format work?

### ISSUE THREAD

**Issue by ba32107** [grafeas/grafeas#449] opened 2020-06-19 17:08 UTC
Hi,

I am trying to understand this file:
https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/swagger/grafeas.swagger.json#L18

For example, in the highlighted line, this is the route path:
`/v1beta1/{name=projects/*/notes/*}`

I am not familiar with the syntax in the named parameter (`{name=projects/*/notes/*}`). What does this mean? Is this valid OpenAPI spec? I was reading through [their documentation](https://swagger.io/docs/specification/describing-parameters/), as well as Google, but I wasn't able to find any info regarding this. I am using [NSwag](https://github.com/RicoSuter/NSwag) to generate C# controller classes from these Swagger specs, but NSwag doesn't understand this format.

This causes a big problem for me, because in my generated code, all paths will end up as `v1beta1/{name}`, which causes conflicts.

I assume this syntax somehow describes what format the `{name}` parameter should take. Considering this, wouldn't it be easier to define the path like this?
`/v1beta1/projects/{project}/notes/{name}`
This looks like it would correspond to standard OpenAPI specs.

Thanks,
Balazs

**Comment by ba32107** [comment] 2020-07-10 15:21
Hi @clrprod and @alexcope, I've pinged you directly because you have changed the swagger files recently, could you give me an insight on the above, please? Thanks.

**Comment by aysylu** [comment] 2020-07-13 16:11
Hi @ba32107,

The issue is the conversion difficulties between the representation of resources in  [Google API](http://cloud/apis/design/resources) and OpenAPI spec. There are known issues in swagger when converting between the two, and while many of them were fixed in the past year, some still remain, eg [described here](https://github.com/grafeas/client-go/pull/15). There are 3 options here at this point:

1) we welcome contributions to fix these in the generated clients, if you're utilizing one from the auto-generated ones,
2) use the proto bindings generated by `protoc` (with the main downside in it not producing idiomatic client code),
3) write own client (and we'd be happy to link to it).

Cheers,
Aysylu

**Comment by ba32107** [comment] 2020-07-13 19:23
Hi @aysylu, thanks for the clarification. I did not think to search among the client repos for this issue.

My use-case is actually server side - I am implementing Grafeas from scratch in C#. I wanted to provide a REST API as well as the Protobuf service, and I was trying to generate my service endpoints based on the Swagger files. Unfortunately, it looks like this is not possible at this point. I am sticking with the Protobuf service for now.

**Comment by aysylu** [comment] 2020-07-14 00:11
Hi @ba32107,

Got it! If you decide to open source the C# client, please let us know and we'd be happy to point to it. Thanks!

I'm marking this resolved, but please feel free to re-open if there's anything else we can help address.

**Closed by aysylu** 2020-07-14 00:11 UTC
