### ISSUE TITLE
Retagging is causing different Go Module content to be fetched from different sources

### ISSUE THREAD

**Issue by elioengcomp** [grafeas/grafeas#377] opened 2019-09-10 20:56 UTC
## Expected Behavior
The tags should be immutable since Go Module Proxies will cache them.

## Actual Behavior
I'm getting 3 different checksums from 3 different sources when running `go mod download`. See the `Sum` field on the outputs below:

GoCenter (GOPROXY=https://gocenter.io) 
```
{
	"Path": "github.com/grafeas/grafeas",
	"Version": "v0.1.0",
	"Info": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.info",
	"GoMod": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.mod",
	"Zip": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.zip",
	"Dir": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/github.com/grafeas/grafeas@v0.1.0",
	"Sum": "h1:V3IyGokvgZ+n/FH1r+0H0hYmvTtgM2KvjkpI1O5dX9k=",
	"GoModSum": "h1:uxn8ZxiAeuGX/IvQZgg3iw66zqOglLlrx8Tj7UMXvV8=",
	"Latest": true
}
```

Google's proxy (GOPROXY=https://proxy.golang.org)
```
{
	"Path": "github.com/grafeas/grafeas",
	"Version": "v0.1.0",
	"Info": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.info",
	"GoMod": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.mod",
	"Zip": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.zip",
	"Dir": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/github.com/grafeas/grafeas@v0.1.0",
	"Sum": "h1:yrWENDvuSGdDUIwpcUY7WsvNRzFjoezgPZFDcGPHSc0=",
	"GoModSum": "h1:uxn8ZxiAeuGX/IvQZgg3iw66zqOglLlrx8Tj7UMXvV8=",
	"Latest": true
}
```

GitHub (GOPROXY=direct):
```
{
	"Path": "github.com/grafeas/grafeas",
	"Version": "v0.1.0",
	"Info": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.info",
	"GoMod": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.mod",
	"Zip": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/cache/download/github.com/grafeas/grafeas/@v/v0.1.0.zip",
	"Dir": "/Users/eliom/workspace/go-modules-example/empty-module/gopath/pkg/mod/github.com/grafeas/grafeas@v0.1.0",
	"Sum": "h1:60sO0aqJJF7rjRCievYIAVlA8ROjoRBW8MKjJ2euuI4=",
	"GoModSum": "h1:uxn8ZxiAeuGX/IvQZgg3iw66zqOglLlrx8Tj7UMXvV8=",
	"Latest": true
}
```

This generates the following error when trying to resolve the module from any source that is not Google's proxy:

```
→ export GOPROXY=direct
→ go get github.com/grafeas/grafeas@v0.1.0
go: finding github.com/grafeas/grafeas v0.1.0
go: downloading github.com/grafeas/grafeas v0.1.0
verifying github.com/grafeas/grafeas@v0.1.0: checksum mismatch
	downloaded: h1:60sO0aqJJF7rjRCievYIAVlA8ROjoRBW8MKjJ2euuI4=
	sum.golang.org: h1:yrWENDvuSGdDUIwpcUY7WsvNRzFjoezgPZFDcGPHSc0=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

## Steps to Reproduce the Problem

1 - Set the proxy to one of the sources below 
2 - Run `go get github.com/grafeas/grafeas@v0.1.0`

**Comment by clrprod** [comment] 2019-09-24 14:32
Yep - I think a tag got moved. sum.golang.org is recording a different version than what we are serving

**Comment by clrprod** [comment] 2019-09-24 14:32
```
GO111MODULE=on GONOSUMDB=* go get github.com/grafeas/grafeas@v0.1.0
go: finding github.com v0.1.0
go: downloading github.com/grafeas/grafeas v0.1.0
go: finding github.com/grafeas v0.1.0
go: extracting github.com/grafeas/grafeas v0.1.0

GO111MODULE=on GOPROXY=direct go get github.com/grafeas/grafeas@v0.1.0
go: finding github.com/grafeas/grafeas v0.1.0
go: downloading github.com/grafeas/grafeas v0.1.0
verifying github.com/grafeas/grafeas@v0.1.0: checksum mismatch
        downloaded: h1:60sO0aqJJF7rjRCievYIAVlA8ROjoRBW8MKjJ2euuI4=
        sum.golang.org: h1:yrWENDvuSGdDUIwpcUY7WsvNRzFjoezgPZFDcGPHSc0=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by clrprod** [comment] 2019-09-24 14:33
I think the only fix is to tag a new version, and make sure to not move that tag.

**Comment by aysylu** [comment] 2019-09-24 18:03
I released [Grafeas v0.1.1](https://groups.google.com/forum/#!topic/grafeas-users/1tP3ltrKXJ8). Could you please try again with the new tag and see if the issue is resolved?

**Comment by clrprod** [comment] 2019-09-24 18:49
0.1.1 seems to be working.

```
GO111MODULE=on go get github.com/grafeas/grafeas@v0.1.1                 
go: finding github.com v0.1.1
go: finding github.com/grafeas v0.1.1
go: extracting github.com/grafeas/grafeas v0.1.1

GOPROXY=https://gocenter.io GO111MODULE=on go get github.com/grafeas/grafeas@v0.1.1
go: finding github.com/grafeas v0.1.1
go: finding github.com v0.1.1

GOPROXY=direct GO111MODULE=on go get github.com/grafeas/grafeas@v0.1.1
```

**Comment by elioengcomp** [comment] 2019-09-30 12:24
`v0.1.1` looks good.

**Comment by aysylu** [comment] 2019-10-01 22:42
Thank you for confirming, @elioengcomp and @clrprod! Closing this issue now.

**Closed by aysylu** 2019-10-01 22:42 UTC
